-- Title: Normalize lesson-author AI HTML block data shape
-- Purpose: Convert AI-generated HTML component data from {"data": "<html>"} to the canonical "<html>" JSONB string shape.
-- Affected schema: public
-- Affected tables: course_blocks
-- Risk level: Low/medium. Scoped to HTML blocks generated by lesson_author_ai with source lesson_author_proposal.
-- Execution owner: User/manual only
-- Direct execution by Codex: Forbidden
-- Backup recommendation: Export matching course_blocks rows before execution, especially id, data, published_data, metadata, updated_at.
-- Notes:
--   Dashboard UnitEditor expects html block data to be a JSONB string.
--   A previous lesson-author apply path incorrectly saved data as an object wrapper: {"data": "<html>"}.
--   This script normalizes existing generated rows. Future rows are fixed in backend code.

BEGIN;

UPDATE course_blocks
SET data = data -> 'data',
    updated_at = now()
WHERE block_type = 'html'
  AND deleted_at IS NULL
  AND metadata ->> 'generated_by' = 'lesson_author_ai'
  AND metadata ->> 'source' = 'lesson_author_proposal'
  AND jsonb_typeof(data) = 'object'
  AND jsonb_typeof(data -> 'data') = 'string';

UPDATE course_blocks
SET published_data = published_data -> 'data',
    updated_at = now()
WHERE block_type = 'html'
  AND deleted_at IS NULL
  AND metadata ->> 'generated_by' = 'lesson_author_ai'
  AND metadata ->> 'source' = 'lesson_author_proposal'
  AND jsonb_typeof(published_data) = 'object'
  AND jsonb_typeof(published_data -> 'data') = 'string';

COMMIT;

-- Verification queries:
-- 1) These should return zero rows after execution:
-- SELECT id, course_id, display_name, data, published_data
-- FROM course_blocks
-- WHERE block_type = 'html'
--   AND deleted_at IS NULL
--   AND metadata ->> 'generated_by' = 'lesson_author_ai'
--   AND metadata ->> 'source' = 'lesson_author_proposal'
--   AND (
--     (jsonb_typeof(data) = 'object' AND jsonb_typeof(data -> 'data') = 'string')
--     OR (jsonb_typeof(published_data) = 'object' AND jsonb_typeof(published_data -> 'data') = 'string')
--   );
--
-- 2) Recently generated lesson-author HTML rows should now have string data:
-- SELECT id, course_id, display_name, jsonb_typeof(data) AS data_type, left(data #>> '{}', 120) AS data_preview
-- FROM course_blocks
-- WHERE block_type = 'html'
--   AND deleted_at IS NULL
--   AND metadata ->> 'generated_by' = 'lesson_author_ai'
--   AND metadata ->> 'source' = 'lesson_author_proposal'
-- ORDER BY updated_at DESC
-- LIMIT 20;
--
-- Rollback SQL, only if you must revert this normalization:
-- BEGIN;
-- UPDATE course_blocks
-- SET data = jsonb_build_object('data', data),
--     updated_at = now()
-- WHERE block_type = 'html'
--   AND deleted_at IS NULL
--   AND metadata ->> 'generated_by' = 'lesson_author_ai'
--   AND metadata ->> 'source' = 'lesson_author_proposal'
--   AND jsonb_typeof(data) = 'string';
--
-- UPDATE course_blocks
-- SET published_data = jsonb_build_object('data', published_data),
--     updated_at = now()
-- WHERE block_type = 'html'
--   AND deleted_at IS NULL
--   AND metadata ->> 'generated_by' = 'lesson_author_ai'
--   AND metadata ->> 'source' = 'lesson_author_proposal'
--   AND jsonb_typeof(published_data) = 'string';
-- COMMIT;
